### ISSUE TITLE
Información sensible

### ISSUE THREAD

**Issue by bregydoc** [olanaso/donde-hay-COVID19#1]
Hola @olanaso, te escribo debido a la publicación de este proyecto. Entiendo la utilidad que buscas que tenga tu desarrollo para la comunidad peruana; sin embargo, déjame explicarte porque considero que deberías darle una vuelta a la idea detrás de tu proyecto.
El primer punto va relacionado con la validez de la data que muestras, no muestras las fuentes y por lo que pude leer usas data de un repositorio de <[arcgis](https://services6.arcgis.com/d6rNtq16iigtXRJ5/ArcGIS/rest/services/GEORREFE_COVID19_LIMA/FeatureServer/0/query?returnGeometry=true&where=1%3D1&outSr=4326&outFields=*&inSr=4326&geometry=%7B%22xmin%22%3A-90%2C%22ymin%22%3A-21.94304553343818%2C%22xmax%22%3A67.5%2C%22ymax%22%3A0%2C%22spatialReference%22%3A%7B%22wkid%22%3A4326%7D%7D&geometryType=esriGeometryEnvelope&spatialRel=esriSpatialRelIntersects&geometryPrecision=6&f=geojson)> cuyo autor es desconocido,  al ser de fuentes desconocidas y no poder garantizar su veracidad esto pone en peligro a los usuarios finales de tu página web ya que estos pueden llegar a conclusiones equivocadas, eso es lo que se llama desinformación. 
El segundo punto tiene que ver con las acciones que pueden tomar los usuarios finales de tu página; tienes que tener en cuenta que muchas personas pueden usar esta información para llevar a cabo acciones incorrectas y que terminen siendo contraproducentes para la emergencia en que nos encontramos, por dar un ejemplo, podrían haber personas que manifiesten racismo, xenofobia o alguna forma de discriminación con los lugares que muestras en el mapa de tu página y eso es algo que puede dividir a nuestra sociedad.

Finalmente, te sugiero que pongas un disclaimer, o mejor aún, busques hacer que la data tenga una capa de privacidad que la haga más valiosa, como ejemplo rápido se me ocurre que no muestres puntos en el mapa, si no, un contador general por distrito, de esta manera evitas vulnerar la privacidad de los lugares muy específicos, por ejemplo, NYT hizo eso [aquí](https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html).

Bueno, espero tu respuesta,
Saludos.

**Comment by olanaso** [comment]
Si recien me entere de la ley ya le di de baja el github pages, gracias por la advertencia.
